version: '3.9-slim'

services:
  dataapi:
    build: .
    container_name: dataapi
    command: python app.py
    ports:
      - "80"
    environment:
      - NAME=World
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network: